<Project Sdk="Microsoft.NET.Sdk.Razor">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Kimlik.Server" />
    <InternalsVisibleTo Include="Kimlik.Server.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kimlik.Application\Kimlik.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" />
  </ItemGroup>

</Project>
