<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kimlik.Domain\Kimlik.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="OpenIddict.EntityFrameworkCore" />
    <PackageReference Include="OpenIddict.Server" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Kimlik.Infrastructure.Tests" />
    <InternalsVisibleTo Include="Kimlik.Server.Tests" />
  </ItemGroup>

</Project>
